# Generated by Django 5.2 on 2026-07-25 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='disaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.disaster'),
        ),
        migrations.AddField(
            model_name='issue',
            name='hazard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hazard'),
        ),
    ]
