# Generated by Django 5.2 on 2026-07-25 09:46

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_issue_disaster_issue_hazard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='hazard',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hazard'),
        ),
    ]
