# Generated by Django 5.2 on 2026-07-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_issue_hazard'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard',
            name='summary',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
