# Generated by Django 5.2 on 2026-07-25 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_alert_message_alter_disaster_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_user_hazard',
        ),
        migrations.AddField(
            model_name='subscription',
            name='disaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.disaster'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('hazard', 'disaster', 'user'), name='unique_user_hazard_disaster'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('disaster__isnull', False), ('hazard__isnull', False), _connector='OR'), name='exists_disaster_hazard'),
        ),
    ]
