# Generated by Django 5.2 on 2026-07-25 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_subscription_unique_user_hazard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_user_hazard_disaster',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='disaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.disaster'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='hazard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hazard'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('hazard', 'user'), name='unique_user_hazard'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('disaster', 'user'), name='unique_user_disaster'),
        ),
    ]
